/**
 * llms.txt auto-generation.
 *
 * Fetches the publisher's sitemap and builds a machine-readable
 * site guide that AI agents can consume in a single request,
 * instead of crawling 5,000 pages.
 *
 * Spec: https://llmstxt.org
 */

const SITEMAP_PATHS = ["/sitemap.xml", "/sitemap_index.xml", "/sitemap-0.xml"];
const MAX_URLS = 500; // cap to keep the file reasonable

/**
 * Generate and return the llms.txt content for a domain.
 * Cached in KV with a 24-hour TTL.
 */
export async function getLlmsTxt(hostname, { CACHE }) {
  const key = `llmstxt:${hostname}`;
  const cached = await CACHE.get(key);
  if (cached) return cached;

  const txt = await buildLlmsTxt(hostname);
  await CACHE.put(key, txt, { expirationTtl: 86400 }); // 24h
  return txt;
}

async function buildLlmsTxt(hostname) {
  const origin = `https://${hostname}`;
  const urls = await fetchSitemapUrls(origin);

  const lines = [
    `# ${hostname}`,
    ``,
    `> This file was auto-generated by XOXO (xoxo.ai) to help AI agents`,
    `> understand this site's structure without crawling every page.`,
    `> Cached and served at the edge. Updated every 24 hours.`,
    ``,
    `## Site`,
    ``,
    `- Homepage: ${origin}/`,
    ``,
    `## Pages`,
    ``,
  ];

  for (const url of urls.slice(0, MAX_URLS)) {
    lines.push(`- ${url}`);
  }

  lines.push(``);
  lines.push(`## Notes`);
  lines.push(``);
  lines.push(`- Full content is served to retrieval agents as structured JSON.`);
  lines.push(`- Training crawlers receive full HTML cached at the edge.`);
  lines.push(`- Origin servers are not contacted for bot requests.`);

  return lines.join("\n");
}

async function fetchSitemapUrls(origin) {
  for (const path of SITEMAP_PATHS) {
    try {
      const res = await fetch(`${origin}${path}`, {
        headers: { "User-Agent": "XOXO/1.0 (llms.txt generator; xoxo.ai)" },
        cf: { cacheTtl: 3600 },
      });
      if (!res.ok) continue;
      const xml = await res.text();
      const urls = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].trim());
      if (urls.length > 0) return urls;
    } catch {
      // try next path
    }
  }
  return [];
}
